param(
    [string]$RepoOwner = "",
    [string]$RepoName = "",
    [string]$OffsetsFile,
    [string]$Version
)


$ghInstalled = Get-Command gh -ErrorAction SilentlyContinue
if (-not $ghInstalled) {
    Write-Host "GitHub CLI (gh) not found. Installing..." -ForegroundColor Yellow
    winget install --id GitHub.cli -e --accept-source-agreements --accept-package-agreements
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to install GitHub CLI. Please install manually from https://cli.github.com/" -ForegroundColor Red
        exit 1
    }

    $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
}


$authStatus = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "Not authenticated with GitHub. Please run: gh auth login" -ForegroundColor Red
    exit 1
}

if ([string]::IsNullOrWhiteSpace($RepoOwner) -or [string]::IsNullOrWhiteSpace($RepoName)) {
    $remoteUrl = git config --get remote.origin.url 2>$null
    if (-not [string]::IsNullOrWhiteSpace($remoteUrl)) {
        if ($remoteUrl -match "github\.com[:/](?<owner>[^/]+)/(?<repo>[^/.]+)(\.git)?$") {
            if ([string]::IsNullOrWhiteSpace($RepoOwner)) {
                $RepoOwner = $Matches.owner
            }
            if ([string]::IsNullOrWhiteSpace($RepoName)) {
                $RepoName = $Matches.repo
            }
        }
    }
}

if ([string]::IsNullOrWhiteSpace($RepoOwner) -or [string]::IsNullOrWhiteSpace($RepoName)) {
    Write-Host "Repo owner/name not provided and could not be inferred from remote.origin.url." -ForegroundColor Red
    Write-Host "Pass -RepoOwner and -RepoName explicitly." -ForegroundColor Yellow
    exit 1
}

if (-not (Test-Path $OffsetsFile)) {
    Write-Host "Offsets file not found: $OffsetsFile" -ForegroundColor Red
    exit 1
}


$date = Get-Date -Format "yyyy-MM-dd"


$releaseNotes = @"


**Version:** $Version
**Date:** $date
**Offsets File:** Offsets.hpp



- Pattern-matched function offsets (luaV_execute, luaH_new, etc.)
- 400+ string offsets for Roblox services and Luau internals
- 300+ structure member offsets
- Clean output with only meaningful named offsets



1. Download `Offsets.hpp` from the assets below
2. Include in your executor project
3. Use the `REBASE` macro for runtime address calculation



- Generic function prologue scanning removed to avoid garbage offsets
- Only pattern-matched named functions are included
- Structure member offsets are hardcoded and stable across versions

---

*Auto-generated by Orion Dumper*
"@


$tagName = "v$Version"


$existingTag = gh release view $tagName --repo "$RepoOwner/$RepoName" 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "Release $tagName already exists. Deleting..." -ForegroundColor Yellow
    gh release delete $tagName --repo "$RepoOwner/$RepoName" --yes
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Failed to delete existing release. You may need to delete the tag manually." -ForegroundColor Red
        Write-Host "Run: git push --delete origin $tagName" -ForegroundColor Yellow
        exit 1
    }
}


Write-Host "Creating GitHub release $tagName..." -ForegroundColor Green
gh release create $tagName `
    --repo "$RepoOwner/$RepoName" `
    --title "Orion Dumper - $Version" `
    --notes "$releaseNotes" `
    $OffsetsFile

if ($LASTEXITCODE -eq 0) {
    Write-Host "Release created successfully!" -ForegroundColor Green
    Write-Host "Release URL: https://github.com/$RepoOwner/$RepoName/releases/tag/$tagName" -ForegroundColor Cyan
} else {
    Write-Host "Failed to create release." -ForegroundColor Red
    exit 1
}
